version: '3'

volumes:
  firmwaredata:
  dbdata:

services:
  flashman:
    image: anlixhub/flashman:local
    volumes:
      - firmwaredata:/app/public/firmwares
    ports:
      - "8000:8000"
    depends_on:
      - flashman-mongodb
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 1883:1883
      - 8883:8883
      - 8000:8000
    env_file:
      - .env_flashman
    networks:
      flm_net:
        aliases:
          - flashman

  flashman-mongodb:
    image: mongo:3.6.1-jessie
    deploy:
      restart_policy:
        condition: on-failure
    restart: "always"
    volumes:
      - dbdata:/data/db:nocopy
    user: root
    networks:
      flm_net:
        aliases:
          - flashman-mongodb
networks:
  flm_net:
    driver: overlay
    driver_opts:
      com.docker.network.enable_ipv6: "false"
